---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - WEBUI_PORT=8800
      - TORRENTING_PORT=21212
    volumes:
      - &{QBITTORRENT_DIR}:/config
      - ${MEDIA}:/downloads/media #optional
    ports:
      - 8800:8800
      - 21212:21212
      - 21212:21212/udp
    restart: unless-stopped
